FROM python:3.11-slim-buster

RUN apt-get update && apt-get install -y --no-install-recommends --no-install-suggests \
    redis-server \
    && pip install --no-cache-dir --upgrade pip \

WORKDIR /app
COPY ./requirements.txt /app
RUN pip install --no-cache-dir -r requirements.txt
COPY . /app

EXPOSE 8000

CMD redis-server --daemonize yes && python3 classification.py